main: me.rayzr522.sunshine.Sunshine
name: Sunshine
version: 1.0.0
description: A Bukkit plugin to remind you to go outside and get some sunshine!
author: Rayzr
#commands:
#  sunshine:
#    description: The main command for Sunshine
#    aliases: [alias1,alias2]
#    usage: "\u00A7cRayzr fracked something up."